#!/usr/bin/env node

import File from 'fs-extra';
import packageJSON from '../package.json';

const KEYS = ['author', 'dependencies', 'description', 'main', 'name', 'version'];
const DATA = KEYS.reduce((object, key) => {
  return Object.assign(object, { [key]: packageJSON[key] });
}, {});

try {
  File.mkdirSync('./app');
} catch (error) {
  if (error.code !== 'EEXIST') {
    throw error;
  }
}

File.copySync('./src/images', './app/images');
File.writeFileSync('./app/index.html', File.readFileSync('./src/index.html'));
File.writeFileSync('./app/package.json', JSON.stringify(DATA));
